spring:
  application:
    name: consumer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8084
server:
  port: 8084
feign:
  hystrix:
    enabled: true